### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by MamadyKonate**
Implemented  ReverseRotor Method for decrypting text in a rotor

### CODE REVIEW

**Comment by Docmilo** [comment]
Hi @MamadyKonate When you create a pull request, you need to pay attention to the branch you want to merge back into. It appears as though you are trying to merge into the repository that you originally [forked  ](https://github.com/Atlantic-Technological-University/CSD) and instead you should merge into the repository that you [forked](https://github.com/leslwingbast/CSD).

**Comment by MamadyKonate** [comment]
Thank you very much @Docmilo for the feedback.
That was a real mess - apologies.
I thought the idea was you first merge into the main of the [forked](https://github.com/leslwingbast/CSD) - as this is the one I cloned from, and once happy, you then merge that into the main of the originally [forked ](https://github.com/Atlantic-Technological-University/CSD) from.
Are you saying that when making a pull request, we should merge directly into the "real" [origin](https://github.com/Atlantic-Technological-University/CSD)?
Thanks again - really appreciated.

**Comment by Docmilo** [comment]
Hi @MamadyKonate,
   The whole purpose of the practical exercise is so that people new to Git and GitHub can make a "real mess" in a safe environment and learn to use the technologies correctly. No need to apologise, 
   
   Take a look at this stackoverflow [article](https://stackoverflow.com/questions/7057194/what-is-the-difference-between-forking-and-cloning-on-github) on the difference between forks and clones. 
   
   When you try to create a pull request, GitHub defaults the target destination of the PR to the original source of the repository. Either the original repository that you forked from or the clone. 

In this image you can see that when we start the process of creating a pull request, GitHub has selected the original repository. In this case the repository that you forked from at the beginning. 
PR1

What you need to do, is select [your forked copy of the repository ](https://github.com/leslwingbast/CSD) (leslwingbast/CSD) as the base repository and then the feature branch you want to merge back into the main branch of your repository. For example
PR2

**Comment by MamadyKonate** [comment]
That was beautifully put @Docmilo - thank you.
I thought I got it first, then I was kind of lost. 
And from this, things are much clearer - all I had to do was to select the [forked ](https://github.com/leslwingbast/CSD/tree/main/Week%204/Enigma%20-%20C%20Sharp/Enigma)as the target instead of the the one forked from ([yours](https://github.com/Atlantic-Technological-University/CSD)).
Thanks again for all your help - appreciated

**Pull request closed without merging**
